### ISSUE TITLE
【開発】登録済ユーザーがログインできるようにする

### ISSUE THREAD

**Issue by naotsukamoto** [shigakijGitHub/rails_work_nj#18]

**Comment by naotsukamoto** [comment]
## できること

- 登録済ユーザーがログインできる
- 新規ユーザーが登録画面(/select/top)に遷移できる

## done定義

- 登録してあるユーザー情報で、/login でログインしたら認証され、/logs/topに遷移できること

## 画面イメージ

![スクリーンショット 2020-04-19 22 37 45](https://user-images.githubusercontent.com/14305735/79689255-73eb7880-828e-11ea-88ee-4098177278a3.png)



https://docs.google.com/presentation/d/135dS-tAD2TWUeJ35vKeuOrKM2FQFR3wG/edit#slide=id.p4

## 技術イメージ

- gem 'devise' を使う

## その他

- ログイン用にtableを作るので、既存の 'users' tableにある下記のカラムは削除する
  - mail_adress
  - password

## todo

### ログインできるようにする実装

- [x] gem 'devise' をGemfileに記載
- [x]  'bundle install'
- [x] 仮想ログインユーザーを 'rails console' で作成
- [x] '/login' のビューの作成
- [x] ログインしていないときの、'/login' のビューの実装
- [ ] ログインしているときは、'/logs/top' へリダイレクトする実装
- [ ] 新規登録する場合は、'/select/top' へ遷移できるようリンクを設置 

### その他処理・対応
- [ ] 既存の 'users' tableから、'mail_adress' と 'password' カラムを削除
- [ ] '/select/top' で登録するメールアドレスとpasswordの保存先を、devise用のtableに保存するよう実装

## 懸念点

- [ ] devise用tableとusers tableのkeyをどうするか決める 

## 参考

- [[初心者] deviseを使ってログイン機能を実装してみよう](https://qiita.com/Orangina1050/items/a16e655519a60f35b394)
